---
kind: pipeline
type: docker
name: default

volumes:
  - name: cache_gradle
    host:
      path: /var/lib/cache

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /opt/android-sdk

  - name: flutter
    image: ghcr.io/lingjhf/flutter-image:3.27.1
    commands:
      - cd android
      - echo -e "sdk.dir=/opt/android-sdk\nflutter.sdk=/opt/flutter" > local.properties

    volumes:
      - name: cache_gradle
        path: /opt/android-sdk

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /opt/android-sdk
