---
kind: pipeline
type: docker
name: default

volumes:
  - name: cache_gradle
    host:
      path: /var/lib/cache

steps:
  - name: flutter
    image: ghcr.io/lingjhf/flutter-image:3.27.1
    commands:
      - cd android
      - echo -e "sdk.dir=/opt/android-sdk\nflutter.sdk=/opt/flutter" > local.properties

    volumes:
      - name: cache_gradle
        path: /opt/android-sdk
