---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - "./.gradle"
    volumes:
      - name: cache
        path: /tmp/cache

  - name: flutter
    image: ghcr.io/lingjhf/flutter-image:3.27.1
    environment:
      GRADLE_USER_HOME: /drone/src
    commands:
      - export GRADLE_USER_HOME=/drone/src/.gradle
      - cd android
      - echo -e "sdk.dir=/opt/android-sdk\nflutter.sdk=/opt/flutter" > local.properties
      - cd ..
      - flutter build apk --verbose
      - ls -a
  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - "./.gradle"
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache
