---
kind: pipeline
type: docker
name: default

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /home/gradle/.gradle

  - name: flutter
    image: ghcr.io/lingjhf/flutter-image:3.27.1
    commands:
      - cd android
      - echo -e "sdk.dir=/opt/android-sdk\nflutter.sdk=/opt/flutter" > local.properties
      - flutter build apk

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /home/gradle/.gradle

volumes:
  - name: cache
    host:
      path: /var/lib/cache
