---
kind: pipeline
type: docker
name: default

steps:
  - name: flutter
    image: ghcr.io/lingjhf/flutter-image:3.27.1
    commands:
      - cd android
      - echo -e "sdk.dir=/opt/android-sdk\nflutter.sdk=/opt/flutter" > local.properties
      - gradle
      - cd ..
      - flutter build apk
